# OpenVPN client + SOCKS proxy
# Usage:
# Create configuration (.ovpn), mount it in a volume
# docker run --volume=something.ovpn:/ovpn.conf:ro --device=/dev/net/tun --cap-add=NET_ADMIN
# Connect to (container):1080
# Note that the config must have embedded certs
# See `start` in same repo for more ideas

FROM debian:stable-slim

COPY entry.sh /

RUN true \
    && apt update \
    && apt install -y openvpn microsocks bash openresolv curl mtr-tiny procps iputils-ping \
    && apt clean \
    && chmod a+x /entry.sh \
    && true

ENTRYPOINT [ \
    "/bin/bash", "-c", \
    "cd /etc/openvpn && /usr/sbin/openvpn --config /openvpn.conf --script-security 2 --route-up /entry.sh" \
    ]
